### ISSUE TITLE
Use counter to find the count of each elements in a list.

### ISSUE THREAD

**Issue by thesprydatasnake** [thesprydatasnake/Python_Use_Cases#2]
## Script Title - Use counter to find the count of each elements in a list. Extend your code to count using another list too.

**Brief** -

ex1: 
```
list1 = [1,1,2,3]
Output:
{1:2, 2:1,3:1}
```

ex2: 
```
list1 = [1,1,2,3]
list2 = [1,2]
Output:
1:2 , 2:1

```

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by batul02** [comment]
Hi, I am a Hacktoberfest participant. Can I contribute to this issue?

**Comment by thesprydatasnake** [comment]
Sure, @batul02

**Comment by batul02** [comment]
Thank you @thesprydatasnake. I will start working on it right away.
