### ISSUE TITLE
Script for calculating the dot product.

### ISSUE THREAD

**Issue by thesprydatasnake** [thesprydatasnake/Python_Use_Cases#3]
## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by herkura** [comment]
can I work on this?

**Comment by thesprydatasnake** [comment]
@herkura Good luck!

**Comment by herkura** [comment]
👍🏻

**Comment by thesprydatasnake** [comment]
Closing via #6
